# Generated by Django 4.2.4 on 2024-03-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_mustvisitplace_popularplace_tour_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('category1', 'Popular places'), ('category2', 'Must Visit Places'), ('category3', 'Packages')], default='', max_length=20),
        ),
    ]
