# Generated by Django 4.2.4 on 2024-03-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='detail_images',
        ),
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.CharField(null=True),
        ),
    ]
